language: julia
os:
  - linux
  - osx
  - windows
before_install:
  - source ${TRAVIS_BUILD_DIR}/test/windows_java.sh
julia:
  - 1.0
  - 1.3
  - nightly

env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1

jobs:
  exclude:
  - os: mac
    env: JULIA_COPY_STACKS=0
  - julia: 1.0
    env: JULIA_COPY_STACKS=0
  - os: windows
    env: JULIA_COPY_STACKS=1
  allow_failures:
  - julia: nightly
  - os: linux
    env: JULIA_COPY_STACKS=0

branches:
  only:
    - master
    - test_async
    - /release-.*/

notifications:
  email: false
