language: julia
os:
        #  - linux
        #  - osx
  - windows
before_install:
  - source ${TRAVIS_BUILD_DIR}/test/windows_java.sh
julia:
  - 1.0
  - 1.3
  - nightly
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11

env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1

matrix:
  allow_failures:
    - julia_version: nightly

branches:
  only:
    - master
    - test_root_task
    - remove_assert
    - /release-.*/

notifications:
  email: false
